const basePath = '/icons'
export const icons = {
  home: `${basePath}/home.svg`,
  arrowRight: `${basePath}/arrow-right.svg`,
  cart: `${basePath}/cart.svg`,
  check: `${basePath}/check.svg`,
  close: `${basePath}/close.svg`,
  clock: `${basePath}/clock.svg`,
  error: `${basePath}/error.svg`,
  fire: `${basePath}/fire.svg`,
  food: `${basePath}/food.svg`,
  heart: `${basePath}/heart.svg`,
  ingredients: `${basePath}/ingredients.svg`,
  meat: `${basePath}/meat.svg`,
  motorcycle: `${basePath}/motorcycle.svg`,
  order: `${basePath}/order.svg`,
  profile: `${basePath}/profile.svg`,
  recipe: `${basePath}/recipe.svg`,
  restaurant: `${basePath}/restaurant.svg`,
  search: `${basePath}/search.svg`,
  share: `${basePath}/share.svg`,
  starFilled: `${basePath}/star-filled.svg`,
  starOutlined: `${basePath}/star-outlined.svg`,
}
