const basePath = '/icons'
export const icons = {
  home: `${basePath}/home.svg`,
  homeActive: `${basePath}/home-active.svg`,
  homeInactive: `${basePath}/home-inactive.svg`,
  arrowRight: `${basePath}/arrow-right.svg`,
  arrowLeft: `${basePath}/arrow-left.svg`,
  cart: `${basePath}/cart.svg`,
  check: `${basePath}/check.svg`,
  close: `${basePath}/close.svg`,
  clock: `${basePath}/clock.svg`,
  warning: `${basePath}/warning.svg`,
  fire: `${basePath}/fire.svg`,
  food: `${basePath}/food.svg`,
  heart: `${basePath}/heart.svg`,
  ingredient: `${basePath}/ingredient.svg`,
  meat: `${basePath}/meat.svg`,
  motorcycle: `${basePath}/motorcycle.svg`,
  order: `${basePath}/order.svg`,
  orderActive: `${basePath}/order-active.svg`,
  orderInactive: `${basePath}/order-inactive.svg`,
  profile: `${basePath}/profile.svg`,
  recipe: `${basePath}/recipe.svg`,
  recipeActive: `${basePath}/recipe-active.svg`,
  recipeInactive: `${basePath}/recipe-inactive.svg`,
  restaurant: `${basePath}/restaurant.svg`,
  search: `${basePath}/search.svg`,
  share: `${basePath}/share.svg`,
  starFilled: `${basePath}/star-filled.svg`,
  starOutlined: `${basePath}/star-outlined.svg`,
  trash: `${basePath}/trash.svg`,
  errorCircle: `${basePath}/error-circle.svg`,
  protein: `${basePath}/protein.svg`,
  carbs: `${basePath}/carbs.svg`,
  plusWhite: `${basePath}/plus-white.svg`,
  cartWhite: `${basePath}/cart-white.svg`,
}
