import type { Metadata } from "next";
import localFont from "next/font/local";
import "./style/globals.css";

const poppins = localFont({
  src: [
    {
      path: '/fonts/poppins-medium-webfont.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '/fonts/poppins-regular-webfont.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/poppins-bold-webfont.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-poppins', 
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
